### ISSUE TITLE
Any Intension for making this work with flutter 3?

### ISSUE THREAD

**Issue by MSOB7YY** [moda20/flutter-tunein#8]
I tried migrating this project with flutter 3 which supports null-safety, fixed over 1.7k errors and it still doesn't work [here is the code (clone null-safety branch)](https://github.com/MSOB7YY/flutter-tunein/tree/null-safety) 
fixes also included replacing some outdated packages with new null-safety-supporting ones (All packages are updated to the last version)

side note: [the main branch here](https://github.com/MSOB7YY/flutter-tunein/tree/main) contains only the outdated packages modification (other packages still uses old version) 

## more information
- building from [main branch](https://github.com/MSOB7YY/flutter-tunein/tree/main) returns null at some point
![Screenshot_20221129_094810](https://user-images.githubusercontent.com/85245079/204635692-7f1476f2-550e-4728-98bd-6b050125b377.png),
which after inspection, turns out it's in line 1702 of musicService.dart 
![Screenshot_20221129_094803](https://user-images.githubusercontent.com/85245079/204636404-7d588f88-371f-446d-b357-5c4e5d76cb0f.png) 
i.e. data is null
then app crashes and exits 
[full error log](https://github.com/MSOB7YY/flutter-tunein/blob/null-safety/error-of-running.txt)

- building from [null-safety branch](https://github.com/MSOB7YY/flutter-tunein/tree/null-safety)  gives `Exception: Gradle task assembleDebug failed with exit code 1`

**Comment by moda20** [comment]
@MSOB7YY First, thanks for trying this update.

From your screenshots it should be an issue with teh audioPlayer plugin i am using. It's a modified version from another plugin that only works for android. So your best bet is to update that to work on flutter 3 and test it using the built in sample project. 

For the build from the null safety branch crashing, this was a known issue from the first version of the flutter update that brought null safety. It is due to many packages, some of them i made, not supporting that. I will be looking into this, the moment i get the flutter dev environment running.

**Comment by MSOB7YY** [comment]
so basically, either upgrading all packages to work with null safety (all project will be using null safety), or upgrading only AudioPlayer plugin (all project will still use non-null safety) ?

**Comment by moda20** [comment]
@MSOB7YY yes, a lot of the plugins i made for this project are not up to date. I would like to better upgrade those or even change them if other plugins are much more developed

**Comment by moda20** [comment]
@MSOB7YY i was able to fix all the issues with all my plugins and updated them to null safety versions 
and i was able to update tuneIn the app itself to a newer version. I pushed a new alpha update with most of the features running correctly. 
So i am closing this issue for now
